model:
  name: 'pfh_osnet'
  pretrained: False
  load_weights: ''
  resume: ''
 
data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_erase']
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]
  save_dir: 'market1501_s/pfh_osmlfn'

loss:
  name: 'triplet'  
  softmax:
    label_smooth: True
  triplet:
    margin: 0.5
    weight_t: 1.0
    weight_x: 1.0
    weight_c: 0.0005

sampler:
  train_sampler: 'RandomIdentitySampler' 
  num_instances: 4

train:
  optim: 'sgd' #
  lr: 0.065
  max_epoch: 350
  batch_size: 64
  # fixbase_epoch: 5
  # open_layers: ['classifier']  
  lr_scheduler: 'multi_step' 
  stepsize: [225, 270, 320]
  staged_lr: False
  seed: 2
  start_epoch: 0
  warmup_total_epoch: 20
  warmup_multiplier: 10

test:
  batch_size: 300
  dist_metric: 'euclidean' 
  normalize_feature: False
  evaluate: False
  eval_freq: 5
  rerank: False
  visactmap: False
  start_eval: 0

cuhk03:
    labeled_images: False
    use_metric_cuhk03: False
